### ISSUE TITLE
Activation payload does not include accountId

### ISSUE THREAD

**Issue by dgvives** [meJevin/Cryptlex.Net#16]
Activation payload does not include `accountId`.

This is a recent addition to the Cryptlex webapi. While at the time of creating the issue is optional, soon will become mandatory to create and update (patch) activations.

https://api.cryptlex.com/v3/docs#tag/Activations/operation/post/v3/activations 

`accountId` is also a new parameter for accounts/login, check updates, and get latest release endpoints

**Comment by meJevin** [comment]
Thanks! I'll get on it as soon as I can 🔥

**Comment by meJevin** [comment]
Fixed this for Activations in #23. Gonna close this issue and open a separate one for other endpoints
